Vagrant.configure("2") do |config|
  config.vm.box = "debian/wheezy64"

  config.vm.network "public_network"


  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y python-dev 
     apt-get install -y python-pip 
     apt-get install build-essential chrpath libssl-dev libxft-dev
  SHELL
end
root@escobar:~
